### ISSUE TITLE
Issue with setuptools

### ISSUE THREAD

**Issue by JTeijema** [J535D165/scitree#5]
```console
> scitree
Traceback (most recent call last):
  File "c:\program files\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "xxx\AppData\Roaming\Python\Python39\Scripts\scitree.exe\__main__.py", line 4, in <module>
  File "xxx\scitree\scitree\__main__.py", line 3, in <module>
    from setuptools_scm import get_version
ModuleNotFoundError: No module named 'setuptools_scm'
```

Directly after installing I get this error on the first run.

**Comment by J535D165** [comment]
Thanks for reporting! Fixed in https://github.com/J535D165/scitree/releases/tag/v0.5.3.
